const ToolManager = require("../tools");

/**
 * ==========================================
 * ToolRouter - Router for tool execution tasks
 * ==========================================
 */
class ToolRouter {
    constructor(kernel) {
        this.kernel = kernel;
    }

    /**
     * Executes the steps generated by the TaskPlanner.
     * @param {Object} plan { steps: [{ tool, args }] }
     * @returns {Promise<Array>} Array of step execution results: [{ tool, args, success, result, error }]
     */
    async route(plan) {
        const results = [];
        if (!plan || !plan.steps || !plan.steps.length) {
            return results;
        }

        for (const step of plan.steps) {
            try {
                console.log(`[ToolRouter] Routing execution to tool: ${step.tool} with args:`, step.args);
                const result = await ToolManager.execute(step.tool, step.args);
                results.push({
                    tool: step.tool,
                    args: step.args,
                    success: true,
                    result
                });
            } catch (error) {
                console.error(`[ToolRouter] Failed executing tool: ${step.tool}`, error);
                results.push({
                    tool: step.tool,
                    args: step.args,
                    success: false,
                    error: error.message
                });
            }
        }

        return results;
    }
}

module.exports = ToolRouter;
